apiVersion: v1
kind: Service
metadata:
  name: student-consumer
  labels:
    run: student-consumer
spec:
  ports:
  - port: 8085
    protocol: TCP
  selector:
    app: student-consumer-selector
  type: NodePort